# Generated by Django 2.2.17 on 2021-04-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentServiceConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_drc",
                    models.ForeignKey(
                        help_text="Document API where new documents will be created.",
                        limit_choices_to={"api_type": "drc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zgw_consumers.Service",
                        verbose_name="primary DRC",
                    ),
                ),
            ],
            options={
                "verbose_name": "document serivce configuration",
                "verbose_name_plural": "document serivce configurations",
            },
        ),
    ]
